CREATE DATABASE LOCADORA;
USE LOCADORA;

CREATE TABLE DESENVOLVEDORAS (
ID_DESENVOLVEDORA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50)
);

CREATE TABLE PUBLISHERS (
ID_PUBLISHER INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50)
);

CREATE TABLE PLATAFORMAS (
ID_PLATAFORMA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50),
ID_DESENVOLVEDORA INT,
FOREIGN KEY (ID_DESENVOLVEDORA) REFERENCES DESENVOLVEDORAS(ID_DESENVOLVEDORA)
);

CREATE TABLE LISTAGENEROS (
ID_LISTAGENERO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50)
);

CREATE TABLE JOGOS (
ID_JOGO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50),
ID_DESENVOLVEDORA INT NOT NULL,
FOREIGN KEY (ID_DESENVOLVEDORA) REFERENCES DESENVOLVEDORAS(ID_DESENVOLVEDORA),
LANCAMENTO YEAR,
ID_PUBLISHER INT NOT NULL,
FOREIGN KEY (ID_PUBLISHER) REFERENCES PUBLISHERS(ID_PUBLISHER),
JOGADORES INT CHECK (JOGADORES >= 1 AND JOGADORES <= 4),
DESCRICAO TEXT, 
ID_PLATAFORMA INT NOT NULL,
FOREIGN KEY (ID_PLATAFORMA) REFERENCES PLATAFORMAS(ID_PLATAFORMA),
DISPONIVEL BOOLEAN DEFAULT 1
);

CREATE TABLE GENEROS (
ID_GENERO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_JOGO INT,
FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(ID_JOGO),
ID_LISTAGENERO INT,
FOREIGN KEY (ID_LISTAGENERO) REFERENCES LISTAGENEROS(ID_LISTAGENERO)
);

CREATE TABLE CLIENTES (
CPF CHAR(11) PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
NASCIMENTO DATE,
ENDERECO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO CHAR(2),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(254) NOT NULL,
SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE EMPRESTIMOS (
ID_EMPRESTIMO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_JOGO INT, 
FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(ID_JOGO),
CPF CHAR(11),
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF),
DATA_EMPRESTIMO DATE,
DATA_ENTREGA DATE,
DEVOLVIDO BOOLEAN DEFAULT 0
);

CREATE TABLE NOTICIAS (
ID_NOTICIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TITULO VARCHAR(50),
CORPO TEXT,
DATA_POST DATE DEFAULT CURDATE()
AUTOR VARCHAR(50),
CREDITO VARCHAR(50)
);

CREATE TABLE ADMINS (
NOME VARCHAR(50) PRIMARY KEY NOT NULL,
SENHA VARCHAR(255)
);

CREATE TABLE RESERVAS (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
CPF CHAR(11) NOT NULL,
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF),
ID_JOGO INT NOT NULL,
FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(ID_JOGO),
DATA_RESERVA DATE DEFAULT (CURRENT_DATE),
PRAZO_RESERVA DATE NOT NULL,
FINALIZAR_RESERVA BOOLEAN DEFAULT 1
); 

CREATE INDEX IDX_JOGOS ON JOGOS (ID_JOGO, NOME, ID_DESENVOLVEDORA, ID_PUBLISHER, ID_PLATAFORMA);

CREATE INDEX IDX_CLIENTES ON CLIENTES (CPF, NOME, EMAIL);
