SELECT J.NOME AS JOGO, P.NOME AS PLATAFORMA, D.NOME AS DESENVOLVEDORA, 
PU.NOME AS PUBLISHER, J.JOGADORES AS 'Nº DE JOGADORES', J.LANCAMENTO AS 'ANO DE LANÇAMENTO', J.DESCRICAO
FROM JOGOS J
INNER JOIN PLATAFORMAS P ON J.ID_PLATAFORMA = P.ID_PLATAFORMA
INNER JOIN DESENVOLVEDORAS D ON J.ID_DESENVOLVEDORA = D.ID_DESENVOLVEDORA
INNER JOIN PUBLISHERS PU ON J.ID_PUBLISHER = PU.ID_PUBLISHER;

SELECT J.NOME AS JOGO, GROUP_CONCAT(LG.NOME SEPARATOR ', ') AS GENEROS
FROM JOGOS J
JOIN GENEROS G ON J.ID_JOGO = G.ID_JOGO
JOIN LISTAGENEROS LG ON G.ID_LISTAGENERO = LG.ID_LISTAGENERO
GROUP BY J.ID_JOGO, J.NOME;

SELECT NOME AS JOGO, LANCAMENTO AS 'ANO DE LANÇAMENTO'
FROM JOGOS
WHERE LANCAMENTO > 2000;

SELECT NOME AS JOGO, LANCAMENTO AS 'ANO DE LANÇAMENTO'
FROM JOGOS
ORDER BY LANCAMENTO DESC;

SELECT NOME AS CLIENTE, EMAIL
FROM CLIENTES
ORDER BY NOME;

SELECT D. NOME AS DESENVOLVEDORA, COUNT(*) AS 'TOTAL DE JOGOS'
FROM JOGOS J
INNER JOIN DESENVOLVEDORAS D ON D.ID_DESENVOLVEDORA = J.ID_DESENVOLVEDORA
GROUP BY D.NOME;

SELECT D. NOME AS DESENVOLVEDORA, COUNT(*) AS TOTAL
FROM JOGOS J
INNER JOIN DESENVOLVEDORAS D ON D.ID_DESENVOLVEDORA = J.ID_DESENVOLVEDORA
GROUP BY D.NOME
HAVING COUNT(*) > 1;

SELECT NOME FROM JOGOS WHERE ID_DESENVOLVEDORA = (SELECT ID_DESENVOLVEDORA FROM JOGOS WHERE NOME = 'MEGA MAN X' LIMIT 1);

SELECT COUNT(*) AS 'TOTAL JOGOS' FROM JOGOS;

SELECT MAX(LANCAMENTO) AS 'MAIS RECENTE', MIN(LANCAMENTO) AS 'MAIS ANTIGO' FROM JOGOS;